### ISSUE TITLE
Syntax proposal for transformations

### ISSUE THREAD

**Issue by loicsander** [typemytype/GlyphConstruction#1]
In the present state, transformations can be achieved by the use of a transformation matrix, following the @ xx, xy, yx, yy, x, y syntax. This syntax could be viewed as ‘too hardcore’ for most users.

Keeping in mind that the syntax should use ascii symbols only, one could imagine a slightly more verbose alternative to the numbers-only matrix.

```
exclamdown = exclam@flip(-1, 1),alignY(top, colon:top)
```

If possible, defining methods could be a way to make transformations relatively straightforward:

### the usual
+ translate(x, y)
+ scale(x, y)
+ rotate(angle)
+ skew(angle)

### specifics
+ alignX(<direction>, <reference>|<number) > i.e. alignX(right, a:right)
+ alignY(<direction>, <reference>|<number) > i.e. alignY(top, colon:top)
+ flip(x, y) (akin to scaling but implicitly scaling at ±100% from the center of the glyph)
or
+ flipX (without argument, even more specific, leaving the use of .scale() for finer scaling tranformations)
+ flipY (idem)
+ …

### reference point
+ origin(0, 0)

In terms of syntax for those methods, I first imagined some comma separated list following the @ sign, but maybe using an attribute-like syntax could be a way to go?

```
exclamdown = exclam.flip(-1, 1).alignY(top, colon:top)
```

**Comment by typemytype** [comment]
a proposal:

using '~' (tilde) in a positioning will flip the mark glyph, as there is control over x and y positioning there is also control over flipx and flip

    questiondown = question@~origin,~top
    gcommaaccent = g + commaaccent@~center,x:~top

**Comment by typemytype** [comment]
the `~`(tilde) is being embedded as flip mark
see https://github.com/typemytype/GlyphConstruction/commit/58482c79a239c5e59624fc442009f7c9a0bff9e3
