### ISSUE TITLE
auto unicode???

### ISSUE THREAD

**Issue by typemytype** [typemytype/GlyphConstruction#12]
if no unicode is provided should it auto generate one?

**Comment by luke-snider** [comment]
I think it would be good to have an option for an auto unicode - e.g. instead of:
aacute = a + acute@top | 00C1
maybe: 
aacute = a + acute@top | autoUnicode

and if it is not possible to assign a unicode, it would be good to be notified I think
(e.g. print: aacute - no unicode was assigned etc.)

**Comment by typemytype** [comment]
Im going to split up your issue see #15

**Comment by typemytype** [comment]
where should it take the autoUnicode data from? GNFUL? only if GNFUL is available?

**Comment by luke-snider** [comment]
I dont know - like the RF autoUnicode() function?

**Comment by gferreira** [comment]
the *Build* options now include a checkbox to automatically set the unicode value when building glyphs:

![building-accented-glyphs_glyph-builder-options](https://user-images.githubusercontent.com/62717/61009778-3d212300-a34a-11e9-85e7-011953e86083.png)

(this issue can be closed)

**Comment by supertype-de** [comment]
Great! Thanks!!!!

J
