### ISSUE TITLE
`#!` as “Add following text as glyph note”

### ISSUE THREAD

**Issue by twardoch** [typemytype/GlyphConstruction#22]
Hi @typemytype 

In the spirit of FeaPyFoFum, we’ve implemented an extension that uses GC comments to add minimal semantics: 

If a comment starts with `#!` instead of `#`, it is interpreted as “Add following text as a glyph note to the generated glyph”.

I think it’s unobtrusive enough. I don’t consider this something that would necessarily need upstreaming, but perhaps you’ll find it interesting. What do you think? 

Cheers,
Adam

**Comment by typemytype** [comment]
see https://github.com/typemytype/GlyphConstruction/blob/master/Lib/glyphConstruction.py#L761

I will change the readme
