### ISSUE TITLE
Unicode gets removed on existing glyphs on build

### ISSUE THREAD

**Issue by typoman** [typemytype/GlyphConstruction#23]
If there is a glyph that already has a Unicode inside the font and I build a glyph construction and rewrite the existing glyphs, the Unicode turns to None for the glyph. These are the glyphs that already existed in the font:

```
finalkafdagesh | FB3A
yodyod | 05F2
```
Here is the formula to build the composites that remove the existing glyphs unciodes:

```
finalkafdagesh = finalkaf + dagesh@center
yodyod = yod & yod
```

Current solution:

```
finalkafdagesh = finalkaf + dagesh@center | FB3A
yodyod = yod & yod | 05F2
```

**Comment by typemytype** [comment]
so you would like that unicode to be more sticky: when its not provided and there is an existing glyph it should keep the existing unicode value?

**Comment by typemytype** [comment]
it could be checked similarly as `markColor`

https://github.com/typemytype/GlyphConstruction/blob/master/LibExtension/glyphConstructionUI.py#L362-L365

**Comment by typemytype** [comment]
@typoman could you test this? before it get pushed to mechanic

thanks!!

**Comment by typoman** [comment]
It works now! Unicodes stay the same if glyphs already exist. Thanks!
