### ISSUE TITLE
saving existing .glyphconstruction file

### ISSUE THREAD

**Issue by typemytype** [typemytype/GlyphConstruction#25]
when (editing then) saving an existing .glyphConstruction file the Glyph Builder asks me under what name and where to save the file instead of simply saving.

see https://github.com/typemytype/GlyphConstruction/blob/master/LibExtension/glyphConstructionUI.py#L673-L680

**Comment by supertype-de** [comment]
Hi, when using a glyph without outline or component (like space) as a source it gets appended to destination glyph. Thus `nbspace = space` will genrate a nbspace glyph with component space. I'm wondering if this is intentional.

**Comment by supertype-de** [comment]
I noticed that color definition needs to be a tuple `$yellow = (1.0, 1.0, 0.0, 1.0)`. Your help description shows a color value without brackets.

**Comment by supertype-de** [comment]
Color value is not picked up when I run this
```
$orange = (1.0, 0.4, 0.0, 0.75)
glyph1 = glyph2 ! {orange} 
```
The glyph cell will simply keep its color that it had before running.

**Comment by typemytype** [comment]
splitter into separate issues, for clarity....

**Comment by supertype-de** [comment]
The file name of the UFO (without the extension) is used when hitting Save in the Glyph Builder instead of the glyphConstruction’s file name

**Comment by typemytype** [comment]
follow issue #33 for opening a .glyphconstruction file directly in RF
