### ISSUE TITLE
Generated glyphs don't trigger unicode automatically

### ISSUE THREAD

**Issue by supertype-de** [typemytype/GlyphConstruction#28]
When I generate new glyphs like `Aring` for example the resulting glyph contains no unicode value. Is that to be expected? I made the assumption that unless a unicode value is defined the name of the glyph will trigger a unicode value if it is according to RF naming scheme. When I add `Aring` via Font > Add Glyphs the correct unicode value is used.

**Comment by gferreira** [comment]
the *Build* options now include a checkbox to automatically set the unicode value when building glyphs:

![building-accented-glyphs_glyph-builder-options](https://user-images.githubusercontent.com/62717/61009778-3d212300-a34a-11e9-85e7-011953e86083.png)

(this issue can be closed)

**Comment by supertype-de** [comment]
👏🏻🤟🏻✊🏻
