### ISSUE TITLE
H-flip problems

### ISSUE THREAD

**Issue by yarmola** [typemytype/GlyphConstruction#37]
Looks that if base glyph has H-flip applied, it places mark glyphs in incorrect location.

Problem lives there:

```
        if not markFixedX:
            baseTransform = markTransformMap.get(baseGlyphX)
            if baseTransform:
                x += baseTransform[4] - advanceWidth
```

If baseGlyph was flipped, its "dx" component of the matrix (which is baseTransform[4]) will be somewhere in baseGlyph.advanceWidth range, as it needed to compensate for baseTransform[0] = -1.

It is more or less the same problem as referenced in #21.

to verify check this recipe:
blablabla=U@~, + l@center,0

expected result:

<img width="169" alt="Screenshot 2019-09-23 at 03 35 47" src="https://user-images.githubusercontent.com/407038/65396841-4fd8bf00-ddb3-11e9-93dd-b7ca7bddb169.png">

actual result:

<img width="329" alt="Screenshot 2019-09-23 at 03 36 44" src="https://user-images.githubusercontent.com/407038/65396845-62eb8f00-ddb3-11e9-8b51-2e3d63e8e0f8.png">

Solution to this problem is to store **unflipped** matrix in markTransformMap.

Solution to #21 is:

replace

```
            width = font[baseGlyph].width
            t = Transform(*baseTransformMatrix)
            width, y = t.transformPoint((width - advanceWidth, 0))
            advanceWidth += width
```

with something like (this is back-port from C++, so code is not verified):

```
            width = font[baseGlyph].width
            t = Transform(*baseTransformMatrix)
            x0, y = t.transformPoint((0, 0))
            x1, y = t.transformPoint((width, 0))
            advanceWidth += abs(x1 - x0)
```

or alternatively, apply unflipped version of baseTransformMatrix as it will be available from solving the positioning problem

**Comment by typemytype** [comment]
thanks!
