### ISSUE TITLE
GlyphConstruction allows "corrupt" components to be created

### ISSUE THREAD

**Issue by colinmford** [typemytype/GlyphConstruction#40]
I was noticing that a glyph construction string like so: `space = ^ 300` would result in a space glyph with the correct width, but would also contain a corrupt component with a baseGlyph of `''`.

Should GlyphConstruction allow components to be placed that result in a malformed glyph?

Also, should GlyphConstruction allow non-existent glyphs to be added as components, like so: `Aglyph = A + nonexistentglyph`? This would result in a glyph with an "A" component, and a component pointing to a non existent glyph.

PR #39 proposes a fix for this issue.

**Comment by typemytype** [comment]
fixed in https://github.com/typemytype/GlyphConstruction/commit/1de0aec8be6bfe749508e73bf1bf66a467d84cf0
