### ISSUE TITLE
An option not to clear the glyph objects on build.

### ISSUE THREAD

**Issue by typoman** [typemytype/GlyphConstruction#41]
I was thinking if the following syntax only would change glyph margins then it's a nice feature that can be used for metrics math. Then a user has saved their metric math in a file and don't have to enter it everytime.

```
P = ^ H, B
```

Right now the above sytnax also clears the glyph outlines. Maybe an option on the build could ask if the user wants the glyph to be cleared on build?

If that sounds good I can create a PR.

**Comment by typoman** [comment]
Maybe these options can be saved inside the glyph construction syntax. Like:

```
$AutoUnicodes = False
$MarkGlyphs = False
```

**Comment by typemytype** [comment]
have split up the issue as one part was UI related and the other request was related to the glyph construction syntax

**Comment by typemytype** [comment]
`space = ^ 100` should already work!!! but it creates an empty glyph

I guess when there are no baseGlyphs and the glyph names exists in the provided font/layer, then the original drawing could be added to the glyph construction glyph.

**Comment by typemytype** [comment]
a new flag will make this possible:

    >a = ^ 40, 50

this will include the drawing of the `a` if the glyph is available in the provided font and sets the margins

**Comment by typoman** [comment]
Thank you so much! this is super ( ͡° ͜ʖ ͡°)
