### ISSUE TITLE
Maybe these options can be saved inside the glyph construction syntax. Like:

### ISSUE THREAD

**Issue by typemytype** [typemytype/GlyphConstruction#43]
Maybe these options can be saved inside the glyph construction syntax. Like:

```
$AutoUnicodes = False
$MarkGlyphs = False
$ClearOutlines = False
```

_Originally posted by @typoman in https://github.com/typemytype/GlyphConstruction/issues/41#issuecomment-575657554_

**Comment by typemytype** [comment]
this could be a handy but only in the UI parts

**Comment by typemytype** [comment]
this will happen with comment variables:

![Screen Shot 2020-01-20 at 22 00 39](https://user-images.githubusercontent.com/1190358/72757463-54ca4580-3bd0-11ea-9ec2-0c5457329628.png)

**Comment by typoman** [comment]
Super nice! Does this mean if there is no comment for MarkGlyphs it would be disabled?

**Comment by typemytype** [comment]
no comment variable means it will take the default

     # MarkGlyphs: False

will disable it
