### ISSUE TITLE
Guidelines and component positioning

### ISSUE THREAD

**Issue by arialcrime** [typemytype/GlyphConstruction#44]
I wanted to quickly align a bunch of accents, so I added global guide called `UCaccent` about 20 units above the cap heigt.
When I construct a letter like the one in the screenshot below I am confused that positioning works that differently between something like `capHeight` and a guide.

<img width="499" alt="Screen Shot 2020-02-06 at 13 10 52" src="https://user-images.githubusercontent.com/2954154/73936068-483d3100-48e2-11ea-8666-3345259196cf.png">

Is there something wrong with my recipe? Shouldn’t these two lines behave more similar? Am I missing something here?

Thanks for the help.

**Comment by typemytype** [comment]
should be fixed!!

but anyhow its more precise to declare both x, y positions. `@UCaccent` is a short notation for `@UCaccent, UCaccent` which is a confusing position as the guide is probably a horizontal one.

A better recipe is: `Egrave = E + gravecomb.case@center,UCaccent`

**Comment by arialcrime** [comment]
Awesome, I’ll implement your recomendation into my recipe.

Thanks for the quick fix!
