### ISSUE TITLE
Building glyphs without UI

### ISSUE THREAD

**Issue by typoman** [typemytype/GlyphConstruction#47]
I have a fixed glyph construction that I want to trigger using a hotkey. I want to write a script that does the construction on the current glyph or selected glyphs in the font window, without having to open the UI. I think this would be very handy if it's tied to a shortcut. But before going ahead I was wondering if you have something already that does this?

Thanks

**Comment by arialcrime** [comment]
Not 100% sure, but maybe this [scripting example](https://robofont.com/documentation/how-tos/building-accented-glyphs-with-a-script/#using-glyphconstruction) in the Robofont documentation helps.

**Comment by typoman** [comment]
Benedikt, Thank you very much! That's what I was looking for.

**Comment by typemytype** [comment]
thanks @arialcrime! to many examples in the RF docs... :)

The extension could actually also store the construction in the glyph lib for later use, this could be handy to rebuild a glyph later on...

**Comment by arialcrime** [comment]
Oh no, there’s never too many examples in the docs! ;-)

Storing the info in the glyph lib sounds like an interesting approach, thanks for the pointer.

**Comment by typoman** [comment]
Thank you Frederik, I was thinking exactly that glyph lib could also be used. That's a very nice approach too. Here is something I made that could be used for rough spacing before proportions are definite:

```py
from glyphConstruction import *
from mojo.UI import CurrentWindow
txt = """
>n = ^ i, i * 0.9
>h = ^ n, n 
>o = ^ i / 3, i / 3
"""

cw = CurrentWindow().doodleWindowName
f = CurrentFont()
selection = []
if cw == 'FontWindow':
    f = CurrentFont()
    s = f.templateSelectedGlyphNames
    for gn in s:
        selection.append(gn)
elif cw == 'GlyphWindow':
    g = CurrentGlyph()
    if g is not None:
        selection.append(g.name)

constructions = ParseGlyphConstructionListFromString(txt)
for c in constructions:
    gn = c.split('=')[0].strip()[1:]
    if gn in selection:
        cg = GlyphConstructionBuilder(c, f)
        g = f[cg.name]
        g.prepareUndo()
        g.leftMargin = cg.leftMargin
        g.width = cg.width
        g.changed()
        g.performUndo()
```

The metrics math I put there is just en example. So if I run this on a set of glyphs or the current glyph, it will apply the metrics math I wrote inside the `txt` construction string to them.

**Comment by typemytype** [comment]
always build the glyph construction and check later if the name of the glyph is not in the selection.

the name of the glyph in a construction could have some formatting...
