### ISSUE TITLE
Set sidebearing of opposite side

### ISSUE THREAD

**Issue by colinmford** [typemytype/GlyphConstruction#48]
Hi @typemytype,

You can currently set the sidebearings of a constructed glyph to be equal to the left side of one glyph, and the right side of another:
```
# left margin is equal to one third of the left margin of A
# right margin is equal to twice the right margin of B
Aacute = A + acute ^ A / 3, B * 2
```
What would you think of adding some sort of syntax so you can set the sidebearings of a glyph to be the opposite side? For instance if I wanted the _right_ side of Aacute to equal 2× the _left_ side of B. I'm not sure what this should look like, but in looking for inspiration, I found @ryanbugden's [SideBear](https://github.com/ryanbugden/Sidebear) uses commas to denote the side from which to take the measurement.

> If you place a comma `,` before or after the glyph name, the opposite SB will be matched. (For example, `,n` input on the LSB of glyph `u` will match the RSB of the `n`.) 

A similar method but a different glyph might make sense (since the comma is already used in Glyph Construction language). It would probably have to be something that A) can't be used in a glyph name and B) not already used in Glyph Construction language

To translate Ryan's example into Glyph Construction language (using `•` as a placeholder for whatever marker is decided):
```
u = n@~origin,~origin ^ n• , •n
```
Which would make a `u` (a flipped `n`) with the _right_ sidebearing of the `n`, set to the _left_ sidebearing of the `u`, and vice versa.

**Comment by ryanbugden** [comment]
Thanks, Colin, great idea to incorporate into GC. 

Just to add two semi-related cents here, I find it super useful in Sidebear, and if this behavior was also added to the Glyph Info inspector pane while you’re at it, that'd be great, and I could directly subclass `GlyphMetricsEditText` :D

**Comment by typemytype** [comment]
well this is already implemented!!!

    B = A ^ 100, A'

enjoy!!

but I see now undocumented...

**Comment by colinmford** [comment]
Oh, thanks!!
