### ISSUE TITLE
Hitting “Save” in Glyph Builder *always* behaves like “Save As…”

### ISSUE THREAD

**Issue by typemytype** [typemytype/GlyphConstruction#52]
requested here: https://forum.robofont.com/topic/884/hitting-save-in-glyph-builder-always-behaves-like-save-as

on open and initial save the path could be stored... and reused on save.

how could a user do a save as? holding alt down? and extra toolbar button?

**Comment by colinmford** [comment]
alt+click might work... though it's not as immediately obvious, I suppose. 

Also as long as the usual `cmd+s = save` and `cmd+shift+s = save as` works, I'm not sure I'll be clicking buttons anyway :)
