### ISSUE TITLE
Multiple Unicodes

### ISSUE THREAD

**Issue by colinmford** [typemytype/GlyphConstruction#62]
Hi @typemytype, 

I might be doing something wrong — but I'm making an all-caps font, and I want to make sure that my glyphs built with GlyphConstruction have two unicodes (one for upper and one for the lowercase). For instance:

I want to build Agrave (U+00C0), but I also want it to have the unicode for the lowercase agrave (U+00E0). I put in
```
Agrave = A + grave @ top | 0x00C0, 0x00E0
```
but it only gets the first unicode. I looked in the source and indeed it only seems possible to set one unicode (unless I am mistaken). 

If I am doing something wrong, please let me know! But if not, do you think we should consider adding the ability to set more than one unicode value?

Thanks!

**Comment by typemytype** [comment]
mmm, for now a construction only has support for a single unicode... 

but I see how this can be a comma separated list of unicodes!

**Comment by colinmford** [comment]
@typemytype Ok, I can make a PR if you would like (might not be right away)

**Comment by typemytype** [comment]
that would be great!

I would opt to always set `unicodes`

happens [here]( https://github.com/typemytype/GlyphConstruction/blob/master/Lib/glyphConstruction.py#L757-L761) and [here](https://github.com/typemytype/GlyphConstruction/blob/master/Lib/glyphConstruction.py#L789)

**Comment by colinmford** [comment]
@typemytype I made PR #63, please give it a test!
