### ISSUE TITLE
Center on body?

### ISSUE THREAD

**Issue by colinmford** [typemytype/GlyphConstruction#64]
Hi @typemytype , I have another enhancement I would like to put out there:

I would like to use GlyphConstruction to make "spacing accents" from my zero-width combining accents (centered on X=0). The OpenType spec recommends the spacing accents sit on a body about the size of the enspace so let's call that 500.

I could do something like `acute = acutecmb ^ 500` but they wouldn't be centered. I would like them to be centered.

I something like `acute = acutecmb @ 1, 0, 0, 1, 250, xHeight ^ 500` gets me close, but GlyphConstruction positions based on the bounding box if I recall so it's still slightly off center (i.e. the xMin of the bbox is placed at 250, not the origin point of the acutecmb). I can do some fine-tuning of those values to make it look centered but it might change per weight, and I try to keep numbers out of my file anyway so I can reuse it for all the styles of the typeface.

So first, can you think of a way to center a glyph (with zero width, but with outlines that overhang) on a body of, say, 500u? And secondly, if not, do you think maybe there should be a "center on body" command? Not sure what it would be right at the moment, but I can think on it.

**Comment by typemytype** [comment]
interesting!

but doable with the current implementation!! 


you subtract the left and right margin if the cmb mark from half of the requested width

```
$accentsWidth = 500

grave = grave.cmb ^ `{accentsWidth}/2+grave.cmb`, `{accentsWidth}/2+grave.cmb`
```

**Comment by colinmford** [comment]
Ok, that works! Thanks, @typemytype!
