### ISSUE TITLE
Change current glyph not working

### ISSUE THREAD

**Issue by benkiel** [typemytype/GlyphConstruction#78]
![CleanShot 2024-02-12 at 12 30 27@2x](https://github.com/typemytype/GlyphConstruction/assets/878741/2cece679-9e8b-4eaa-b7c0-2b2258bdc973)

Tried to use the change current glyph notation, seems not to be changing focus of the current glyph

**Comment by benkiel** [comment]
Turns out this works for `top`, but not for `top,top`

**Comment by typemytype** [comment]
`mark@A:center, B:top` will place the mark glyph centered over the `A`  and  at the top of the `B`
