### ISSUE TITLE
See the computed position of selected glyph

### ISSUE THREAD

**Issue by LettError** [typemytype/GlyphConstruction#9]
Together with the preview it would be useful to be able to see the computed (final) position of the components in the selected glyph. For instance when trying to match a specific position.

**Comment by LettError** [comment]
It is at the bottom of the screen, staring me in the face.

**Comment by cjdunn** [comment]
I just found this preview in the corner, it's very nice! Possible bug: it doesn't update live. 

As a user I'm trying to match an existing accented glyph. I see the preview in the main window update as I move anchors around, which is great. But the overlay preview in the corner doesn't update until I click another glyph and then click back. I would expect that these would both update live.

![preview_not_updating](https://user-images.githubusercontent.com/3900241/55902383-5ecb0c80-5b99-11e9-825e-024f4666ab60.png)
